version: '3.1'
services:
  zookeeper:
    container_name: local-zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
