version: '3.1'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    networks:
      - my-network
  app:
    image: test:latest
    build:
      context: .
    container_name: app
    depends_on:
      - zookeeper
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
